sudo: required
services:
  - docker

language: python
python:
  - 3.6

install:
  - docker build -t storm-${role}-${ver} ./alpine/${ver}/storm-${role}
  - docker run -d -p 127.0.0.1:80:80 --name storm-${role}-${ver} storm-${role}-${ver}

script:
  - docker ps | grep -q storm-${role}-${ver}

notifications:
  slack: frcubigdata:UHa7tsq87e6C0xd0C8es5CQO

env:
  matrix:
    - role=base               ver=1.0.2
    - role=nimbus             ver=1.0.2
    - role=supervisor         ver=1.0.2
    - role=ui                 ver=1.0.2

branches:
  only:
    - master